name: open_fashion
description: Open Fashion is a free eCommerce UI

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  dio: ^5.0.0
  logger: ^1.1.0
  google_fonts: ^3.0.1
  loading_indicator: ^3.1.0
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^2.0.1
  flutter_swiper_plus: ^2.0.4
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^8.0.0
  package_info_plus: ^1.4.2
  animated_text_kit: ^4.2.2
  collection: ^1.17.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_name: ^0.0.1
  flutter_lints: ^2.0.1

flutter_launcher_name:
  name: "Open Fashion"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/media/
    - assets/icons/

  fonts:
    - family: TenorSans
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
